GET http://localhost:3000/students

###

POST http://localhost:3000/students
content-type: application/json

{
    "firstName": "Hatim",
    "lastName": "Naimi"
}

###

GET http://localhost:3000/students/2

###

GET http://localhost:3000/students/2/classes

###

DELETE http://localhost:3000/students/2